use university;

show tables;

INSERT INTO TEACHERS
VALUES
(3, 'YOGI' , 'WD', 3);

INSERT INTO studentS (id, name, AGE, MARKS)
VALUES (1, 'MADHU', 23 , 87);


INSERT INTO students
(id, name, gender, AGE, MARKS ,passed)
VALUES 
(4, 'Rayan', 'Male',25 , 82 , 'NO'),
(5, 'Reshma', 'Female',21 , 89 , 'YES');


CREATE TABLE COURSE
(ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(20)
);

INSERT INTO COURSE 
(NAME)
VALUES
('MATHS'),
('PHYSICS'),
('JAVA');


CREATE TABLE top_students (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    marks INT
);

ALTER TABLE top_students
MODIFY COLUMN ID INT AUTO_INCREMENT;

INSERT INTO TOP_STUDENTS
(NAME , MARKS)
SELECT
 NAME , MARKS
FROM STUDENTS
WHERE MARKS > 80;

SELECT NAME AS FULL_NAME
FROM students;

SELECT DISTINCT MARKS AS UNIQUE_MARKS
FROM STUDENTS;

SET SQL_SAFE_UPDATES = 0;

UPDATE STUDENTS
SET GENDER = 'MALE'
WHERE NAME = 'SIVA';

DELETE FROM STUDENTS
WHERE NAME = 'MADHU';

SELECT * FROM TEACHERS;
SELECT * FROM STUDENTS;
SELECT * FROM COURSE;
SELECT * FROM TOP_STUDENTS;
