SELECT * FROM EMPLOYEE;

-- Display departments that have more than one employee.
SELECT 
DEPARTMENT , COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING TOTAL_EMPLOYEES > 1;


-- Find departments whose total salary is greater than ₹60,000.
SELECT DEPARTMENT , SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING TOTAL_SALARY > 60000;

-- Display cities whose average salary is greater than ₹50,000.
SELECT CITY , AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY CITY
HAVING AVG_SALARY > 50000;

-- Find departments where the maximum salary is greater than ₹60,000.
SELECT DEPARTMENT , MAX(SALARY) AS MAXI_SALARY
FROM EMPLOYEE 
GROUP BY DEPARTMENT
HAVING MAXI_SALARY > 60000;

-- Consider only employees earning more than ₹40,000 and display departments having at least two such employees.
SELECT DEPARTMENT , COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
WHERE SALARY > 40000
GROUP BY DEPARTMENT
HAVING TOTAL_EMPLOYEES >= 2;


ALTER TABLE EMPLOYEE
RENAME TO EMPLOYEE3;

 SHOW TABLES;
