USE company;

CREATE TABLE DEPARTMENT (
	DEPARTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(20) NOT NULL UNIQUE,
    LOCATION VARCHAR(20) DEFAULT 'HYDERABAD'
);

CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
	EMPLOYEE_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) UNIQUE,
	SALARY DECIMAL(10,2) DEFAULT 25000,
    JOINDATE DATE NOT NULL,
    EMPLOYEE_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    DEPARTMENT_ID INT,
    
    CONSTRAINT CHCEK_EMPLOYEE_SALARY
    CHECK ( SALARY >= 15000 ),
    
    CONSTRAINT CHECK_EMPLOYEE_STATUS
    CHECK (EMPLOYEE_STATUS IN ('ACTIVE','INACTIVE')),
    
    CONSTRAINT FK_DEPARTMENT_ID
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

DESCRIBE EMPLOYEE;

INSERT INTO DEPARTMENT
(DEPARTMENT_NAME , LOCATION)
VALUES
('IT', 'HYDERABAD'),
('HR', 'Chennai'),
('Sales', 'Bengaluru');

SELECT * FROM DEPARTMENT;

INSERT INTO employee
    (employee_name, email, salary, joindate, department_id)
VALUES
    ('Siva Kumar', 'siva@gmail.com', 65000, '2024-01-15', 1),
    ('Rakesh', 'rakesh@gmail.com', 45000, '2023-06-10', 2),
    ('Murali', 'murali@gmail.com', 55000, '2022-03-20', 3);
    
SELECT * FROM EMPLOYEE;

SHOW CREATE TABLE EMPLOYEE;

UPDATE EMPLOYEE
SET SALARY = 50000
WHERE EMPLOYEE_ID = 2;

DELETE FROM DEPARTMENT
WHERE DEPARTMENT_NAME = 'SALES';

show tables;

alter table employee
rename to employee_5;

alter table department
rename to department_2;